easy_admin:
    site_name: 'Ynovagroup'
    design:
        brand_color: '#68bc80'
        assets:
            css:
                - 'css/easyadmin.css' 
    entities:
        Sociétés:
            class: App\Entity\Company
        Documents:
            class: App\Entity\Files
        Utilisateurs:
            class: App\Entity\User
        Rôles:
            class: App\Entity\Role

