controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
 
backend:
    resource: ../../src/Controller/Backend/
    prefix: /backend
    name_prefix: backend_
    type: annotation

api:
    resource: ../../src/Controller/Api/
    name_prefix: api_
    type: annotation