backend:
    resource: ../../src/Controller/Backend/
    prefix: /backend
    name_prefix: backend_
    type: annotation

api:
    resource: ../../src/Controller/Api/
    name_prefix: api_
    type: annotation
    
controllers:
    resource: ../../src/Controller/Frontend/
    type: annotation

