#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
    path: /logout

new_password:
    path: /mot-de-passe-oublie/{email}
    controller: App\Controller\PasswordCustomController::newPassword